### ISSUE TITLE
The Index Decoder cannot load in the other Javascript files, CORS is blocking them in chrome

### ISSUE THREAD

**Issue by Tumble7** [NuclearLighthouseStudios/Cassette-Video-Decoder#4]
Chromes Stupid system is blocking cv and cv.decoder from loading in, do i have to use another browser to get this to work? it worked before but i guess chrome got bugged the first time or something

**Comment by NuclearLighthouseStudios** [comment]
Where are you loading the files from? Depending on the browser it can vary a bit, but for the audio stuff to work correctly they need to be served up by a web server, and if it's not hosted on localhost you usually also need https.

**Comment by Tumble7** [comment]
oh, whats the best free web server you recommend?

**Comment by NuclearLighthouseStudios** [comment]
Well, if you already have python installed you can just serve it locally by running `python -m http.server` in the directory where your files are and then access them on http://localhost:8000/

**Comment by Tumble7** [comment]
i got it to work with the python server you suggested. Thx!
